### ISSUE TITLE
"\t" "\n" "\r" "\b" "\\" are rendered first in the math environment

### ISSUE THREAD

**Issue by jizhou-wu** [markomanninen/md2notion#1]
Hi thank you for providing such a useful tool to convert the md to notion. However, when I used it, I met something wrong for the math formula rendering.

For example, in the math invironment

```latex
\begin{align*}
\tilde{a}+b&\to \left[a+b+c\right]\rho\\
c+d&\neq \left[a+b+c\right]\rho
\end{align*}
```
which should be rendered as

$$
\begin{align*}
\tilde{a}+b&\to \left[a+b+c\right]\rho\\
c+d&\neq \left[a+b+c\right]\rho
\end{align*}
$$

However, it will first recognize the regex patterns 
- "\t" as "Tab"
- "\n" as "line feed character"
- "\r" as "Carriage return character"
- "\b" as "word boundary"
- "\\" as "\"
- ....

Then it renders the math. This rendering processing will make the formula fail to be rendered corretly. For example, the above equation may be rendered as

```latex
egin{align*}
ilde{a}+b&   o \left[a+b+c
ight]
ho\\
c+d&
eq \left[a+b+cight]
ho
\end{align*}
```
after first rendering these regex pattern, then render the math as

$$
egin{align*}
ilde{a}+b&   o \left[a+b+c
ight]
ho\
c+d&
eq \left[a+b+cight]
ho
\end{align*}
$$

Will be there any plan for fixing such bug?

**Comment by markomanninen** [comment]
Thank you for the note. I did not make any extensive tests with math equations. Do you have any fix suggestion to commit?

**Comment by jizhou-wu** [comment]
I have tried one step:

move 
```python
text_parts = replace_part(text_parts, inline_katex_pattern, replace_katex)
```
two lines before in the `core.py`. That is to parse the math first then parse the `_` ` _` pattern for bold pattern and `*` `*` for italic pattern. It can solve some of the problems I mentioned above. 

But problems of `\t` `\n` ... still remain. These are recognized by python and thus cannot be safe in the math environment. 

Now I just manually preprocess my markdown text: manually replace `\` to `\\` in the text editor in batch then copy paste for md2notiton for the notion conversion. Then it works. I have tried to use python for this preprocess but nothing lucky happens. Do you have any suggestion?

**Comment by jizhou-wu** [comment]
Just solve this issue. In addition to placing the `text_parts = replace_part(text_parts, inline_katex_pattern, replace_katex)` two lines above in `core.py` to avoid `_` in the math environment is renderd first, the md file should be read by `read()` instead of copy-paste in the triple quotations so that python will not render the `\n` etc.
